### ISSUE TITLE
XRTpy Example notebook not displayed correct due to software  code issue

### ISSUE THREAD

**Issue by joyvelasquez** [HinodeXRT/xrtpy#264] opened 2024-07-03 17:45 UTC
### Bug description

Unexpected errors and malfunctions (“Glitch”) on some notebooks (NB):
Effective Area NB
Temperature Response NB
Using temperature_from_filter_ratio to analyze XRT data NB
Deriving temperatures using composite images and the filter ratio method NB

**Comment by jslavin** [comment] 2024-08-29 17:40
This problem is related to downloading images within the notebooks, which in turn has to do with a problem with the TLS/SSL certificate for xrt.cfa.harvard.edu and the data archive there.

**Comment by jslavin** [comment] 2024-10-24 14:43
The Effective Area and Temperature response figures are fixed now.
Using temperature_from_filter_ratio is still not working with this error showing up on the readthedocs page:

WARNING: SunpyUserWarning: Importing sunpy.net without its extra dependencies may result in errors.
The following packages are not installed:
['drms>=0.7.1', 'zeep>=4.1.0']
To install sunpy with these dependencies use `pip install sunpy[net]` or `pip install sunpy[all]` for all extras.
If you installed sunpy via conda, please report this to the community channel: https://matrix.to/#/#sunpy:openastronomy.org [sunpy.util.sysinfo]

That error also is present in the "Using deconvolve to deconvolve images" example.

The "Deriving temperatures using composite images and the filter ratio method" is still showing the error related to downloading files from xrt.cfa.harvard.edu website, even though it seems that the problem is fixed.

I'd also note that the SunpyUserWarning does not occur when I run those notebooks locally. So it has to do with the environment in which the readthedocs notebooks are executed.

**Comment by wtbarnes** [comment] 2024-10-25 05:48
This is happening because those examples use parts of `sunpy` with particular dependencies for searching for and downloading data. To fix this,  add `sunpy[net]` to the docs dependencies in `pyproject.tml`. I'll note that this is already fixed in #295.

**Comment by joyvelasquez** [comment] 2024-10-25 05:49
Ah, I see. Thanks for the note Will.

**Comment by nabobalis** [comment] 2024-12-12 23:15
I think this has been fixed with the documentation refactor.

**Closed by nabobalis** 2024-12-12 23:15 UTC
Labels: bug, documentation
